"""universal_uuid

Revision ID: 1c703e50512d
Revises: 
Create Date: 2026-07-23 11:29:25.455284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c703e50512d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dosen',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nidn', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dosen_email'), 'dosen', ['email'], unique=True)
    op.create_index(op.f('ix_dosen_id'), 'dosen', ['id'], unique=False)
    op.create_index(op.f('ix_dosen_nidn'), 'dosen', ['nidn'], unique=True)
    op.create_table('mata_kuliah',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kode_mk', sa.String(), nullable=False),
    sa.Column('nama_mk', sa.String(), nullable=False),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.Column('semester_tawaran', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mata_kuliah_id'), 'mata_kuliah', ['id'], unique=False)
    op.create_index(op.f('ix_mata_kuliah_kode_mk'), 'mata_kuliah', ['kode_mk'], unique=True)
    op.create_table('mahasiswa',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nim', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('angkatan', sa.Integer(), nullable=False),
    sa.Column('prodi', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('AKTIF', 'CUTI', 'DROP_OUT', 'LULUS', name='statusmahasiswa'), nullable=False),
    sa.Column('ipk', sa.Float(), nullable=True),
    sa.Column('ips', sa.Float(), nullable=True),
    sa.Column('presensi_persen', sa.Float(), nullable=True),
    sa.Column('total_sks', sa.Integer(), nullable=True),
    sa.Column('dosen_pa_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dosen_pa_id'], ['dosen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mahasiswa_email'), 'mahasiswa', ['email'], unique=True)
    op.create_index(op.f('ix_mahasiswa_id'), 'mahasiswa', ['id'], unique=False)
    op.create_index(op.f('ix_mahasiswa_nim'), 'mahasiswa', ['nim'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('dosen_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dosen_id'], ['dosen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('akademik_semester',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mahasiswa_id', sa.Uuid(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('ipk', sa.Float(), nullable=False),
    sa.Column('ips', sa.Float(), nullable=False),
    sa.Column('persentase_kehadiran', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_akademik_semester_id'), 'akademik_semester', ['id'], unique=False)
    op.create_table('catatan_konseling',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mahasiswa_id', sa.Uuid(), nullable=False),
    sa.Column('dosen_id', sa.Uuid(), nullable=False),
    sa.Column('tanggal', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kategori', sa.Enum('AKADEMIK', 'FINANSIAL', 'KESEHATAN', 'PRIBADI', 'LAINNYA', name='kategorimasalah'), nullable=False),
    sa.Column('catatan_teks', sa.Text(), nullable=False),
    sa.Column('catatan_cleansed', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dosen_id'], ['dosen.id'], ),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catatan_konseling_id'), 'catatan_konseling', ['id'], unique=False)
    op.create_table('ews_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mahasiswa_id', sa.Uuid(), nullable=False),
    sa.Column('tingkat_risiko', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='tingkatrisiko'), nullable=False),
    sa.Column('skor_risiko', sa.Integer(), nullable=False),
    sa.Column('pemicu_risiko', sa.JSON(), nullable=False),
    sa.Column('analisis_xai', sa.Text(), nullable=False),
    sa.Column('rekomendasi_intervensi', sa.JSON(), nullable=False),
    sa.Column('status_penanganan', sa.Enum('PENDING', 'IN_PROGRESS', 'RESOLVED', name='statuspenanganan'), nullable=False),
    sa.Column('catatan_penanganan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ews_alerts_id'), 'ews_alerts', ['id'], unique=False)
    op.create_table('nilai_mata_kuliah',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mahasiswa_id', sa.Uuid(), nullable=False),
    sa.Column('mata_kuliah_id', sa.Uuid(), nullable=False),
    sa.Column('dosen_pengajar_id', sa.Uuid(), nullable=False),
    sa.Column('semester_diambil', sa.Integer(), nullable=False),
    sa.Column('nilai_angka', sa.Float(), nullable=False),
    sa.Column('nilai_huruf', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dosen_pengajar_id'], ['dosen.id'], ),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.id'], ),
    sa.ForeignKeyConstraint(['mata_kuliah_id'], ['mata_kuliah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nilai_mata_kuliah_id'), 'nilai_mata_kuliah', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nilai_mata_kuliah_id'), table_name='nilai_mata_kuliah')
    op.drop_table('nilai_mata_kuliah')
    op.drop_index(op.f('ix_ews_alerts_id'), table_name='ews_alerts')
    op.drop_table('ews_alerts')
    op.drop_index(op.f('ix_catatan_konseling_id'), table_name='catatan_konseling')
    op.drop_table('catatan_konseling')
    op.drop_index(op.f('ix_akademik_semester_id'), table_name='akademik_semester')
    op.drop_table('akademik_semester')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_mahasiswa_nim'), table_name='mahasiswa')
    op.drop_index(op.f('ix_mahasiswa_id'), table_name='mahasiswa')
    op.drop_index(op.f('ix_mahasiswa_email'), table_name='mahasiswa')
    op.drop_table('mahasiswa')
    op.drop_index(op.f('ix_mata_kuliah_kode_mk'), table_name='mata_kuliah')
    op.drop_index(op.f('ix_mata_kuliah_id'), table_name='mata_kuliah')
    op.drop_table('mata_kuliah')
    op.drop_index(op.f('ix_dosen_nidn'), table_name='dosen')
    op.drop_index(op.f('ix_dosen_id'), table_name='dosen')
    op.drop_index(op.f('ix_dosen_email'), table_name='dosen')
    op.drop_table('dosen')
    # ### end Alembic commands ###
