"""create table ews_alerts

Revision ID: b93891e4619e
Revises: dd739034d3f1
Create Date: 2026-07-23 09:56:21.166992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93891e4619e'
down_revision: Union[str, Sequence[str], None] = 'dd739034d3f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ews_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mahasiswa_id', sa.Integer(), nullable=False),
    sa.Column('tingkat_risiko', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='tingkatrisiko'), nullable=False),
    sa.Column('skor_risiko', sa.Integer(), nullable=False),
    sa.Column('pemicu_risiko', sa.JSON(), nullable=False),
    sa.Column('analisis_xai', sa.Text(), nullable=False),
    sa.Column('rekomendasi_intervensi', sa.JSON(), nullable=False),
    sa.Column('status_penanganan', sa.Enum('PENDING', 'IN_PROGRESS', 'RESOLVED', name='statuspenanganan'), nullable=False),
    sa.Column('catatan_penanganan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ews_alerts_id'), 'ews_alerts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ews_alerts_id'), table_name='ews_alerts')
    op.drop_table('ews_alerts')
    # ### end Alembic commands ###
