"""create table mahasiswa, dosen and catatan_konseling

Revision ID: dd739034d3f1
Revises: c6376aa19504
Create Date: 2026-07-23 07:51:19.919140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd739034d3f1'
down_revision: Union[str, Sequence[str], None] = 'c6376aa19504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dosen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nidn', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dosen_email'), 'dosen', ['email'], unique=True)
    op.create_index(op.f('ix_dosen_id'), 'dosen', ['id'], unique=False)
    op.create_index(op.f('ix_dosen_nidn'), 'dosen', ['nidn'], unique=True)
    op.create_table('mahasiswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('angkatan', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AKTIF', 'CUTI', 'DROP_OUT', 'LULUS', name='statusmahasiswa'), nullable=False),
    sa.Column('ipk', sa.Float(), nullable=True),
    sa.Column('ips', sa.Float(), nullable=True),
    sa.Column('presensi_persen', sa.Float(), nullable=True),
    sa.Column('total_sks', sa.Integer(), nullable=True),
    sa.Column('dosen_pa_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dosen_pa_id'], ['dosen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mahasiswa_email'), 'mahasiswa', ['email'], unique=True)
    op.create_index(op.f('ix_mahasiswa_id'), 'mahasiswa', ['id'], unique=False)
    op.create_index(op.f('ix_mahasiswa_nim'), 'mahasiswa', ['nim'], unique=True)
    op.create_table('catatan_konseling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mahasiswa_id', sa.Integer(), nullable=False),
    sa.Column('dosen_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kategori', sa.Enum('AKADEMIK', 'FINANSIAL', 'KESEHATAN', 'PRIBADI', 'LAINNYA', name='kategorimasalah'), nullable=False),
    sa.Column('catatan_teks', sa.Text(), nullable=False),
    sa.Column('catatan_cleansed', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dosen_id'], ['dosen.id'], ),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catatan_konseling_id'), 'catatan_konseling', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catatan_konseling_id'), table_name='catatan_konseling')
    op.drop_table('catatan_konseling')
    op.drop_index(op.f('ix_mahasiswa_nim'), table_name='mahasiswa')
    op.drop_index(op.f('ix_mahasiswa_id'), table_name='mahasiswa')
    op.drop_index(op.f('ix_mahasiswa_email'), table_name='mahasiswa')
    op.drop_table('mahasiswa')
    op.drop_index(op.f('ix_dosen_nidn'), table_name='dosen')
    op.drop_index(op.f('ix_dosen_id'), table_name='dosen')
    op.drop_index(op.f('ix_dosen_email'), table_name='dosen')
    op.drop_table('dosen')
    # ### end Alembic commands ###
